# Configuration file for running the test suite. Results typically at http://travis-ci.org/kimpepper/drupal
# whitelist
language: php
php:
  - 5.3
  - 5.4
before_script:
  # Install Apache and FastCGI extension to connect to PHP-FPM.
  - sudo apt-get update > /dev/null
  - sudo apt-get install apache2 libapache2-mod-fastcgi > /dev/null
  - sudo a2enmod rewrite actions fastcgi alias
  - sudo cp -f core/misc/travis-ci/vhost.conf /etc/apache2/sites-available/default
  - sudo sed -i -e "s,/var/www,`pwd`,g" /etc/apache2/sites-available/default
  - sudo apachectl restart

  # Start PHP-FPM. There is no process manager available to start PHP-FPM on
  # Travis CI currently, so we have to locate and enable it manually.
  - sudo cp $HOME/.phpenv/versions/`php -r "print PHP_VERSION;"`/etc/php-fpm.conf.default $HOME/.phpenv/versions/`php -r "print PHP_VERSION;"`/etc/php-fpm.conf
  - $HOME/.phpenv/versions/`php -r "print PHP_VERSION;"`/sbin/php-fpm

  # Install drush from latest master
  - mkdir vendor
  - git clone https://github.com/drush-ops/drush.git vendor/drush
  - chmod +x vendor/drush/drush

  # Import the PHP configuration.
  - phpenv config-add core/misc/travis-ci/php.ini

  # Set MySQL configuration and create the database.
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e 'create database drupal;'

  # Install Backdrop with Drush.
  - chmod a+w sites/default
  - vendor/drush/drush si --db-url=mysql://travis:@localhost/drupal -y
  - chmod go-w sites/default
  - vendor/drush/drush en simpletest -y
script: php -d display_errors="stderr" ./core/scripts/run-tests.sh --php `which php` --concurrency 12 --url 'http://localhost' --color "$TEST_GROUPS"
after_failure:
  - echo "Failures detected. Outputing additional logs:"
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/mysql/error.log
env:
  - TEST_GROUPS='Action,Aggregator,AJAX,Authentication,Ban,Batch API,Block,Book,Bootstrap,Breakpoint,Cache,CKEditor,Color,Comment,Common,Condition API,Configuration,Contact,Content Translation UI,Contextual,Custom Block,Database,Datetime,DbLog,DrupalKernel,Edit,Entity,Entity API,Entity Reference'
  - TEST_GROUPS='Field API,Field types,Field UI,File,File API,File API (remote),Filter,Form API,Forum,HAL,Help,History,Image,Installer,Key-value store,Language,Locale,Lock,Mail,Menu,Minimal,Module,Node,Overlay,Pager,ParamConverter,Path,Path API,Picture,Plugin API,Queue,RDF,REST,Routing,Search,Serialization,Service Provider'
  - TEST_GROUPS='Session,Shortcut,SimpleTest,Standard,Statistics,Syslog,System,Taxonomy,TempStore,Text Editor,Theme,Toolbar,Tour,Tracker,Translation,Transliteration,Typed Data API,Update,Update API,Upgrade path,User,UUID,Views,Views Config,Views Handlers,Views module integration,Views Plugins,Views UI,Views Wizard,XML-RPC,PHPUnit'

